linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
    enable:
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goanalysis_metalinter
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec (gas)
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-use-default: false

  exclude-rules:
    - path: pkg/crypto/ccm
      text: "L' should not be capitalized"
      linters:
        - gocritic
    - path: cipher_suite
      text: "should not use ALL_CAPS in Go names; use CamelCase instead"
      linters:
        - stylecheck
    - path: cipher_suite
      text: "don't use ALL_CAPS in Go names; use CamelCase"
      linters:
        - golint

run:
  skip-dirs-use-default: false
