linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - dupl
    - gocyclo
    - gochecknoglobals
    - funlen

issues:
  exclude-use-default: false

  exclude-rules:
    - path: internal/crypto/ccm
      text: "L' should not be capitalized"
      linters:
        - gocritic
    - path: cipher_suite
      text: "don't use ALL_CAPS in Go names; use CamelCase"
      linters:
        - golint

run:
  skip-dirs-use-default: false
