language: go

branches:
  only:
  - master

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      go: "1.13.x"
      install: skip
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.18.0
      script:
        - bash .github/assert-contributors.sh
        - bash .github/lint-disallowed-functions-in-library.sh
        - bash .github/lint-commit-message.sh
        - golangci-lint run ./...
    - stage: test
      go:
        - "1.12.x"
        - "1.13.x"
      before_install:
        - go mod download
      install: go build ./...
      before_script:
        - rm -rf examples # Remove examples, no test coverage for them
      script:
        - go test -coverpkg=$(go list ./... | tr '\n' ',') -coverprofile=cover.out -v -race -covermode=atomic ./...
      after_success:
        - travis_retry bash <(curl -s https://codecov.io/bash)

