language: go

branches:
  only:
  - master

go:
  - "1.x" # use the latest Go release

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: lint
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.18.0
      install: skip
      script:
        - bash .github/assert-contributors.sh
        - bash .github/lint-disallowed-functions-in-library.sh
        - bash .github/lint-commit-message.sh
        - golangci-lint run ./...
    - stage: test
      before_script:
        - rm -rf examples # Remove examples, no test coverage for them
      before_install:
        - go mod download
      install:
        - go build ./...
      script:
        - go test -coverpkg=$(go list ./... | tr '\n' ',') -coverprofile=cover.out -v -race -covermode=atomic ./...
      after_success:
        - travis_retry bash <(curl -s https://codecov.io/bash)

