name: E2E
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  e2e-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          docker build -t pion-dtls-e2e -f e2e/Dockerfile .
          docker run -i --rm pion-dtls-e2e
