# SPDX-FileCopyrightText: 2026 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

name: Interoperability

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: interop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  interop:
    uses: pion/dtls-interop/.github/workflows/interop-tests.yaml@main
    with:
      dtls-repository: ${{ github.repository }}
      dtls-ref: ${{ github.event.pull_request.head.sha || github.sha }}
